const sb=window.supabase.createClient(YZ_CONFIG.SUPABASE_URL,YZ_CONFIG.SUPABASE_ANON_KEY);let lang=localStorage.getItem('yz-lang')||'ar';let offers=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.getElementById('langToggle').textContent=lang==='ar'?'English':'العربية';document.querySelectorAll('[data-ar][data-en]').forEach(e=>e.textContent=lang==='ar'?e.dataset.ar:e.dataset.en);renderGeneral();fillSelect()}
async function loadOffers(){const r=await sb.from('offers').select('*').eq('active',true).order('category').order('sort_order').order('id');if(r.error){console.error(r.error);return}offers=r.data||[];renderGeneral();fillSelect()}
function renderGeneral(){const box=document.getElementById('generalOffers');if(!box)return;const arr=offers.filter(o=>o.category==='general');box.innerHTML=arr.map(o=>`<article class="price-card"><span class="num">${Number(o.price).toFixed(0)}</span><span class="currency">ريال</span><h3>${esc(lang==='ar'?o.name_ar:o.name_en)}</h3><p>${esc(lang==='ar'?o.description_ar||'':o.description_en||'')}</p><button class="btn primary" onclick="pick(${o.id})">${lang==='ar'?'اختيار':'Choose'}</button></article>`).join('')}
function fillSelect(){const s=document.getElementById('offerSelect');if(!s)return;const service=document.getElementById('serviceType').value;const arr=offers.filter(o=>o.category===service);s.innerHTML=arr.map(o=>`<option value="${o.id}">${esc(lang==='ar'?o.name_ar:o.name_en)} • ${Number(o.price).toFixed(0)} ${lang==='ar'?'ريال':'SAR'}</option>`).join('')||`<option value="">${lang==='ar'?'اختر الخدمة أولًا':'Choose a service first'}</option>`}
function pick(id){const o=offers.find(x=>x.id===id);if(!o)return;document.getElementById('serviceType').value=o.category;fillSelect();document.getElementById('offerSelect').value=String(id);document.getElementById('booking').scrollIntoView({behavior:'smooth'})}
document.getElementById('serviceType').addEventListener('change',fillSelect);document.getElementById('langToggle').addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';localStorage.setItem('yz-lang',lang);applyLanguage()});
document.getElementById('bookingForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),o=offers.find(x=>String(x.id)===String(f.get('offer_id'))),code='YZ-'+crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase(),msg=document.getElementById('bookingMsg');msg.textContent=lang==='ar'?'جارٍ إرسال الحجز...':'Sending booking...';const payload={booking_code:code,customer_name:f.get('customer_name'),customer_phone:f.get('customer_phone'),booking_date:f.get('booking_date'),booking_time:f.get('booking_time'),guests:Number(f.get('guests')),offer_id:o?.id||null,offer_name_snapshot:o?(lang==='ar'?o.name_ar:o.name_en):null,price_snapshot:o?.price??null,service_type:f.get('service_type'),notes:f.get('notes')||null,status:'new'};const r=await sb.from('bookings').insert(payload);if(r.error){console.error(r.error);msg.textContent=lang==='ar'?'تعذر تسجيل الحجز. حاول مرة أخرى.':'Booking could not be submitted. Please try again.';return}msg.textContent=lang==='ar'?`تم تسجيل الحجز بنجاح. رقم الحجز: ${code}`:`Booking submitted. Code: ${code}`;e.target.reset();fillSelect()});
document.querySelector('[name="booking_date"]').min=new Date().toISOString().slice(0,10);applyLanguage();loadOffers();
