-- Yellow Zone: قاعدة البيانات الأساسية
-- نفّذ الملف كاملًا في Supabase SQL Editor.
-- ملاحظة: لا تضع Service Role Key في الواجهة الأمامية.

create extension if not exists pgcrypto;

create table if not exists public.offers (
  id bigint generated by default as identity primary key,
  name_ar text not null,
  name_en text not null,
  description_ar text,
  description_en text,
  price numeric(10,2) not null default 0,
  image_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title_ar text not null,
  title_en text not null,
  body_ar text,
  body_en text,
  image_url text,
  target_url text not null default "/",
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_code text unique not null,
  customer_name text not null,
  phone text not null,
  visit_date date not null,
  people_count integer not null check (people_count between 1 and 100),
  offer_id bigint references public.offers(id) on delete set null,
  offer_name_snapshot_ar text,
  offer_name_snapshot_en text,
  price_snapshot numeric(10,2),
  notes text,
  status text not null default 'new'
    check (status in ('new','confirmed','completed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create index if not exists offers_active_sort_idx
  on public.offers(active, sort_order);

create index if not exists announcements_active_sort_idx
  on public.announcements(active, sort_order);

create index if not exists bookings_visit_date_idx
  on public.bookings(visit_date);

create index if not exists bookings_status_idx
  on public.bookings(status);

alter table public.offers enable row level security;
alter table public.announcements enable row level security;
alter table public.bookings enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Public can read active offers" on public.offers;
create policy "Public can read active offers"
on public.offers for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins manage offers" on public.offers;
create policy "Admins manage offers"
on public.offers for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read active announcements" on public.announcements;
create policy "Public can read active announcements"
on public.announcements for select
to anon, authenticated
using (
  active = true
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at >= now())
);

drop policy if exists "Admins manage announcements" on public.announcements;
create policy "Admins manage announcements"
on public.announcements for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can create bookings" on public.bookings;
create policy "Public can create bookings"
on public.bookings for insert
to anon, authenticated
with check (
  status = 'new'
  and people_count between 1 and 100
);

drop policy if exists "Admins read bookings" on public.bookings;
create policy "Admins read bookings"
on public.bookings for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins update bookings" on public.bookings;
create policy "Admins update bookings"
on public.bookings for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins manage admin users" on public.admin_users;
create policy "Admins manage admin users"
on public.admin_users for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.offers
(name_ar,name_en,description_ar,description_en,price,sort_order)
select * from (values
('باقة المرح','Fun Package','تفاصيل الباقة تُضاف من لوحة الإدارة.','Package details are managed from the admin dashboard.',0,1),
('باقة العائلة','Family Package','تفاصيل الباقة تُضاف من لوحة الإدارة.','Package details are managed from the admin dashboard.',0,2),
('باقة خاصة','Special Package','تفاصيل الباقة تُضاف من لوحة الإدارة.','Package details are managed from the admin dashboard.',0,3)
) v
where not exists (select 1 from public.offers);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists offers_updated_at on public.offers;
create trigger offers_updated_at before update on public.offers
for each row execute function public.set_updated_at();

drop trigger if exists announcements_updated_at on public.announcements;
create trigger announcements_updated_at before update on public.announcements
for each row execute function public.set_updated_at();

drop trigger if exists bookings_updated_at on public.bookings;
create trigger bookings_updated_at before update on public.bookings
for each row execute function public.set_updated_at();
